---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-master-operator
  template:
    metadata:
      labels:
        name: mysql-master-operator
    spec:
      serviceAccountName: mysql-master
      containers:
        - name: mysql-master-operator
          image: "docker.io/shkatara/mysql-master-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mysql-master-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
